### PR TITLE
Optional argument on Browser#wait 

### PR DESCRIPTION
**Pull request by jondruse**
In sites that use javascript very heavily, the Browser#wait method will cause celerity to wait for upto 10 seconds before becoming available.  This is only useful if what you need to interact with is controlled by javascript.  If not, then you're waiting for nothing.  10 seconds is a long time and should be configurable to be shorter.  In any case, when you absolutely need to wait for javascript, you could pass a custom timeout to Browser#wait.

The relavent changes are in a43e5c2b    but I couldn't figure out how to create a pull request for just that one.  Thanks!

### CODE REVIEW

**Comment by jondruse** [comment]
Sorry I got that commit wrong.  Here it is.

https://github.com/centraldesktop/celerity/commit/a43e5c2bee3a7fc8beead486403f202aaf96c64b

**Comment by jarib** [comment]
Could you add a test in spec/browser_spec.rb as well? Just browser.webclient.should_receive(:waitForBackgroundJavaScript) with the right args (for both the default and the explicit timeout).

**Comment by jondruse** [comment]
I will make those changes.  Thanks!

**Comment by jondruse** [comment]
Jari, Please look over these and let me know if there's any issues.  Thanks!

**Pull request merged**
